const fs = require('fs'), vm = require('vm'), assert = require('assert');
const nodes = {}, storage = {};
const node = () => ({ value: '', textContent: '', innerHTML: '', firstChild: {textContent:''}, style: {}, dataset: {}, classList: { toggle() {} }, setAttribute() {}, addEventListener() {}, checkValidity() { return true; } });
const context = vm.createContext({ document: { documentElement: {}, getElementById: id => nodes[id] ??= node(), querySelector: selector => nodes[selector] ??= node(), querySelectorAll: () => [] }, localStorage: { getItem: () => null, setItem: (k, v) => storage[k] = v }, Intl, crypto: require('crypto').webcrypto, setTimeout, clearTimeout });
vm.runInContext(fs.readFileSync('dist/app.js', 'utf8'), context);
vm.runInContext('add("Apples", "Produce", 2, 3); add("Milk", "Dairy & eggs", 1, 4); state.items[0].done = true; save();', context);
assert.equal(nodes.total.textContent, '$10.00');
assert.equal(nodes.bought.textContent, '$6.00');
assert.equal(nodes.left.textContent, '$4.00');
assert.equal(JSON.parse(storage['basket-v1']).items.length, 2);
vm.runInContext('filter = "remaining"; render();', context);
assert(!nodes.items.innerHTML.includes('Apples'));
assert(nodes.items.innerHTML.includes('Milk'));
vm.runInContext('state.budget = 5; render();', context);
assert(nodes['budget-message'].textContent.includes('over'));
vm.runInContext('add("<script>", "Produce");', context);
assert(nodes.items.innerHTML.includes('&lt;script&gt;'));
console.log('Passed totals, basket amounts, filtering, persistence, budget status, and input escaping.');
vm.runInContext(fs.readFileSync('dist/vietnam.js','utf8'),context);
assert(nodes['templates-title'].textContent.includes('đi chợ'));
assert.equal((nodes['template-grid'].innerHTML.match(/data-template=/g)||[]).length,26);
vm.runInContext('state.items=[]; applyTemplate(4);',context);
assert.equal(JSON.parse(storage['basket-v1']).items.length,8);
assert.equal(JSON.parse(storage['basket-v1']).language,'vi');
vm.runInContext('applyTemplate(4);',context);
assert.equal(JSON.parse(storage['basket-v1']).items.length,8);
vm.runInContext('state.items[0].done=true; applyTemplate(4);',context);
assert.equal(JSON.parse(storage['basket-v1']).items.length,9);
vm.runInContext("$('template-search').value='phở'; renderTemplates();",context);
assert.equal((nodes['template-grid'].innerHTML.match(/data-template=/g)||[]).length,1);
vm.runInContext("$('template-search').value=''; $('template-kind').value='dish'; renderTemplates();",context);
assert.equal((nodes['template-grid'].innerHTML.match(/data-template=/g)||[]).length,21);
vm.runInContext("state.language='en'; state.currency='USD'; render();",context);
assert.equal(nodes['templates-title'].textContent,'A little inspiration for your next shop');
assert.equal(nodes.total.textContent,'$0.00');
assert.equal(nodes['template-kind'].value,'dish');
console.log('Passed 20 templates, ingredient search, meal filters, duplicate handling, Vietnamese persistence, English switching, and preserved filters.');
vm.runInContext("$('template-kind').value='all'; $('template-diet').value='vegetarian'; renderTemplates();",context);
assert.equal((nodes['template-grid'].innerHTML.match(/data-template=/g)||[]).length,8);
assert(!nodes['template-grid'].innerHTML.includes('Beef pho'));
vm.runInContext("$('template-search').value='nấm'; renderTemplates();",context);
assert(nodes['template-grid'].innerHTML.includes('Mushroom and tofu soup'));
vm.runInContext("$('template-search').value=''; $('template-diet').value='savory'; renderTemplates();",context);
assert.equal((nodes['template-grid'].innerHTML.match(/data-template=/g)||[]).length,18);
assert(!nodes['template-grid'].innerHTML.includes('Tofu in tomato sauce'));
vm.runInContext(fs.readFileSync('dist/editor.js','utf8'),context);
assert(vm.runInContext("updateIngredient(state.items[0].id,{name:'Nấm',category:'Produce',qty:'0.5',unit:'kg',price:'40000'})",context));
assert.equal(nodes.total.textContent,'$20,000.00');
assert.equal(nodes.bought.textContent,'$20,000.00');
assert.equal(JSON.parse(storage['basket-v1']).items[0].unit,'kg');
assert(!vm.runInContext("updateIngredient(state.items[0].id,{name:'',category:'Produce',qty:1,price:0})",context));
assert(!vm.runInContext("updateIngredient(state.items[0].id,{name:'Nấm',category:'Produce',qty:-1,price:0})",context));
assert(!vm.runInContext("updateIngredient(state.items[0].id,{name:'Nấm',category:'Produce',qty:1,price:Infinity})",context));
assert(vm.runInContext("updateIngredient(state.items[0].id,{name:'<script>',category:'Pantry',qty:2,unit:'gói',price:''})",context));
assert(nodes.items.innerHTML.includes('&lt;script&gt;'));
assert.equal(nodes.total.textContent,'$0.00');
vm.runInContext("state.language='vi'; render();",context);
assert.equal(nodes['template-diet'].value,'savory');
console.log('Passed vegetarian/savory filters, combined search, editable ingredients, decimal quantities, custom units, price totals, persistence, validation, and escaping.');
vm.runInContext(fs.readFileSync('dist/navigation.js','utf8'),context);
assert.equal(nodes['recipes-panel'].hidden,true);
assert.equal(nodes['shopping-panel'].hidden,false);
vm.runInContext("showMainTab('recipes'); state.language='en'; save();",context);
assert.equal(nodes['recipes-panel'].hidden,false);
assert.equal(nodes['shopping-panel'].hidden,true);
assert.equal(nodes['tab-recipes'].textContent,'Templates & meal ideas');
assert.equal(nodes['template-diet'].value,'savory');
vm.runInContext("showMainTab('shopping');",context);
assert.equal(nodes['recipes-panel'].hidden,true);
assert.equal(nodes['shopping-panel'].hidden,false);
assert.equal(JSON.parse(storage['basket-v1']).items[0].name,'<script>');
console.log('Passed default shopping tab, tab switching, language updates, and preserved list and meal filters.');
