const fs = require('fs'), vm = require('vm'), assert = require('assert');
const nodes = {}, storage = {};
const node = () => ({ value: '', textContent: '', innerHTML: '', firstChild: {textContent:''}, style: {}, dataset: {}, children:[], attributes:{}, classList: { toggle() {} }, setAttribute(key,value) { this.attributes[key]=value; }, getAttribute(key) { return this.attributes[key]; }, addEventListener() {}, append(...children) { this.children.push(...children); }, insertBefore(child) { this.children.push(child); return child; }, checkValidity() { return true; }, showModal() {}, close() {}, focus() {} });
const context = vm.createContext({ document: { documentElement: {}, body:node(), getElementById: id => nodes[id] ??= node(), querySelector: selector => nodes[selector] ??= node(), querySelectorAll: () => [], createElement: () => node() }, localStorage: { getItem: () => null, setItem: (k, v) => storage[k] = v }, Intl, crypto: require('crypto').webcrypto, setTimeout, clearTimeout });
vm.runInContext(fs.readFileSync('dist/app.js', 'utf8'), context);
vm.runInContext('add("Apples", "Produce", 2, 3); add("Milk", "Dairy & eggs", 1, 4); state.items[0].done = true; save();', context);
assert.equal(nodes.total.textContent, '$10.00');
assert.equal(nodes.bought.textContent, '$6.00');
assert.equal(nodes.left.textContent, '$4.00');
assert.equal(JSON.parse(storage['basket-v1']).items.length, 2);
vm.runInContext('filter = "remaining"; render();', context);
assert(!nodes.items.innerHTML.includes('Apples'));
assert(nodes.items.innerHTML.includes('Milk'));
vm.runInContext('state.budget = 5; render();', context);
assert(nodes['budget-message'].textContent.includes('over'));
vm.runInContext('add("<script>", "Produce");', context);
assert(nodes.items.innerHTML.includes('&lt;script&gt;'));
console.log('Passed totals, basket amounts, filtering, persistence, budget status, and input escaping.');
vm.runInContext(fs.readFileSync('dist/vietnam.js','utf8'),context);
assert(nodes['templates-title'].textContent.includes('đi chợ'));
assert.equal((nodes['template-grid'].innerHTML.match(/data-template=/g)||[]).length,26);
vm.runInContext('state.items=[]; applyTemplate(4);',context);
assert.equal(JSON.parse(storage['basket-v1']).items.length,8);
assert.equal(JSON.parse(storage['basket-v1']).language,'vi');
vm.runInContext('applyTemplate(4);',context);
assert.equal(JSON.parse(storage['basket-v1']).items.length,8);
vm.runInContext('state.items[0].done=true; applyTemplate(4);',context);
assert.equal(JSON.parse(storage['basket-v1']).items.length,9);
vm.runInContext("$('template-search').value='phở'; renderTemplates();",context);
assert.equal((nodes['template-grid'].innerHTML.match(/data-template=/g)||[]).length,1);
vm.runInContext("$('template-search').value=''; $('template-kind').value='dish'; renderTemplates();",context);
assert.equal((nodes['template-grid'].innerHTML.match(/data-template=/g)||[]).length,21);
vm.runInContext("state.language='en'; state.currency='USD'; render();",context);
assert.equal(nodes['templates-title'].textContent,'A little inspiration for your next shop');
assert.equal(nodes.total.textContent,'$0.00');
assert.equal(nodes['template-kind'].value,'dish');
vm.runInContext("add('Coffee','Pantry',1,4);state.currency='VND';$('currency').value='VND';add('Fish','Meat & seafood',1,30000);render();",context);
assert(nodes.total.textContent.includes('₫'));
assert(nodes['budget-message'].textContent.includes('Budget is set in USD'));
assert(nodes['budget-message'].textContent.includes('other currencies are excluded'));
vm.runInContext("state.budgetCurrency='VND';render();",context);
assert(nodes['budget-message'].textContent.includes('over your budget'));
vm.runInContext("state.currency='USD';$('currency').value='USD';state.items=state.items.filter(item=>!['Fish','Coffee'].includes(item.name));render();",context);
console.log('Passed 20 templates, ingredient search, meal filters, duplicate handling, Vietnamese persistence, English switching, and preserved filters.');
vm.runInContext("$('template-kind').value='all'; $('template-diet').value='vegetarian'; renderTemplates();",context);
assert.equal((nodes['template-grid'].innerHTML.match(/data-template=/g)||[]).length,8);
assert(!nodes['template-grid'].innerHTML.includes('Beef pho'));
vm.runInContext("$('template-search').value='nấm'; renderTemplates();",context);
assert(nodes['template-grid'].innerHTML.includes('Mushroom and tofu soup'));
vm.runInContext("$('template-search').value=''; $('template-diet').value='savory'; renderTemplates();",context);
assert.equal((nodes['template-grid'].innerHTML.match(/data-template=/g)||[]).length,18);
assert(!nodes['template-grid'].innerHTML.includes('Tofu in tomato sauce'));
vm.runInContext(fs.readFileSync('dist/editor.js','utf8'),context);
assert(vm.runInContext("updateIngredient(state.items[0].id,{name:'Nấm',category:'Produce',qty:'0.5',unit:'kg',price:'40000'})",context));
assert(vm.runInContext("updateIngredient(state.items[0].id,{name:'Nấm',category:'Produce',qty:'0.5',unit:'kg',price:'40000',actualPrice:'45000'})",context));
assert.equal(vm.runInContext('state.items[0].price',context),40000);
assert.equal(vm.runInContext('state.items[0].actualPrice',context),45000);
assert.equal(vm.runInContext('state.items[0].actualCurrency',context),'USD');
assert.equal(JSON.parse(storage['basket-v1']).purchaseHistory[0].actualUnitPrice,45000);
assert(nodes['budget-message'].textContent.includes('Actual spend'));
assert(vm.runInContext("updateIngredient(state.items[0].id,{name:'Nấm',category:'Produce',qty:'0.5',unit:'kg',price:'40000',priceCurrency:'VND',actualPrice:'45000',actualCurrency:'USD'})",context));
assert(nodes['budget-message'].textContent.includes('no comparable estimate'));
assert(vm.runInContext("updateIngredient(state.items[0].id,{name:'Nấm',category:'Produce',qty:'0.5',unit:'kg',price:'40000',priceCurrency:'USD',actualPrice:'45000',actualCurrency:'USD'})",context));
vm.runInContext("state.currency='EUR'; render();",context);
assert(!nodes['budget-message'].textContent.includes('Actual spend'));
vm.runInContext("state.currency='USD'; render();",context);
assert.equal(nodes.total.textContent,'$20,000.00');
assert.equal(nodes.bought.textContent,'$20,000.00');
assert.equal(JSON.parse(storage['basket-v1']).items[0].unit,'kg');
assert(!vm.runInContext("updateIngredient(state.items[0].id,{name:'',category:'Produce',qty:1,price:0})",context));
assert(!vm.runInContext("updateIngredient(state.items[0].id,{name:'Nấm',category:'Produce',qty:-1,price:0})",context));
assert(!vm.runInContext("updateIngredient(state.items[0].id,{name:'Nấm',category:'Produce',qty:1,price:Infinity})",context));
assert(vm.runInContext("updateIngredient(state.items[0].id,{name:'<script>',category:'Pantry',qty:2,unit:'gói',price:''})",context));
assert(nodes.items.innerHTML.includes('&lt;script&gt;'));
assert.equal(nodes.total.textContent,'$0.00');
vm.runInContext("state.language='vi'; render();",context);
assert.equal(nodes['template-diet'].value,'savory');
vm.runInContext("state.purchaseHistory.push({itemId:'prior',key:normalizedPurchaseKey('<script>','gói'),currency:'USD',actualUnitPrice:7.5,purchasedAt:new Date().toISOString()});state.items.push({id:'new-item',name:'<script>',category:'Pantry',qty:1,price:0,unit:'gói',done:false});openIngredientEditor('new-item');",context);
assert(nodes['edit-purchase-history'].textContent.includes('$7.50'));
console.log('Passed vegetarian/savory filters, combined search, editable ingredients, decimal quantities, custom units, price totals, persistence, validation, and escaping.');
vm.runInContext(fs.readFileSync('dist/navigation.js','utf8'),context);
assert.equal(nodes['recipes-panel'].hidden,true);
assert.equal(nodes['shopping-panel'].hidden,false);
vm.runInContext("showMainTab('recipes'); state.language='en'; save();",context);
assert.equal(nodes['recipes-panel'].hidden,false);
assert.equal(nodes['shopping-panel'].hidden,true);
assert.equal(nodes['tab-recipes'].textContent,'Templates & meal ideas');
assert.equal(nodes['template-diet'].value,'savory');
vm.runInContext("showMainTab('shopping');",context);
assert.equal(nodes['recipes-panel'].hidden,true);
assert.equal(nodes['shopping-panel'].hidden,false);
assert.equal(JSON.parse(storage['basket-v1']).items[0].name,'<script>');
console.log('Passed default shopping tab, tab switching, language updates, and preserved list and meal filters.');
vm.runInContext("filter='done'; setShoppingMode(true);",context);
assert.equal(vm.runInContext('filter',context),'remaining');
assert.equal(vm.runInContext('shoppingMode',context),true);
assert.equal(vm.runInContext("shoppingModeToggle.getAttribute('aria-pressed')",context),'true');
assert(nodes.items.innerHTML.includes('&lt;script&gt;'));
vm.runInContext("state.items.find(item=>item.id==='new-item').done=true; save();",context);
assert(!nodes.items.innerHTML.includes('&lt;script&gt;'));
vm.runInContext('setShoppingMode(false);',context);
assert.equal(vm.runInContext('filter',context),'done');
assert.equal(vm.runInContext('shoppingMode',context),false);
console.log('Passed focused shopping mode, immediate removal of checked items, and filter restoration.');
const legacyNodes={};
const legacyContext=vm.createContext({
 document:{documentElement:{},body:node(),getElementById:id=>legacyNodes[id]??=node(),querySelector:selector=>legacyNodes[selector]??=node(),querySelectorAll:()=>[],createElement:()=>node()},
 localStorage:{getItem:key=>key==='basket-v1'?JSON.stringify({currency:'EUR',budget:50,items:[{id:'legacy',name:'Rice',category:'Pantry',qty:2,price:4,done:false}]}):null,setItem(){}},
 Intl,crypto:require('crypto').webcrypto,setTimeout,clearTimeout
});
vm.runInContext(fs.readFileSync('dist/app.js','utf8'),legacyContext);
assert.equal(vm.runInContext('state.items[0].priceCurrency',legacyContext),'EUR');
assert.equal(vm.runInContext('state.budgetCurrency',legacyContext),'EUR');
assert(legacyNodes.total.textContent.includes('€'));
console.log('Passed migration of legacy prices and budgets without changing their numeric amounts.');
